account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import (
    UserLoginForm, PwdResetForm, PwdResetConfirmForm,
)
from django.views.generic import TemplateView

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url= 'password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset') ,
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns =  [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('shopsw.urls', namespace='shopsw')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopsw/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'shopsw'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('category/<slug:category_slug>', views.product_list, name='category_list'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('about_us/', views.about_us, name='about_us'),
    path('faqs/', views.faqs, name='faqs'),
    path('contact/', views.contact, name='contact'),
]

templates/includes/footer.html
{% load i18n %}
<div id="templatemo_wrapper">



    <div id="templatemo_footer">
        <p><a href="/">{% trans "Home" %}</a> | <a href="{% url "shopsw:about_us" %}">{% trans "About" %}</a> | <a href="{% url "shopsw:faqs" %}">{% trans "FAQs" %}</a> | <a href="{% url "shopsw:contact" %}">{% trans "Contact Us" %}</a>
        </p>
        Copyright © 2021 <a href="#">SK</a> <!-- Credit: www.templatemo.com --></div> <!-- END of templatemo_footer -->

</div> 

templates/includes/header.html
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}
<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_header">
        <div id="site_title">
            {% if LANGUAGE_CODE == 'en' %}
            <h1><a href="/en/">
            {% elif LANGUAGE_CODE == 'ru' %}
            <h1><a href="/ru/">
            {% endif %}
            {% trans "Online Shoes Store" %}
            </a></h1>
        </div>
        <div id="header_right">
            <p>
            {% if LANGUAGE_CODE == 'ru' %}
            <a href="/en/{{ request.get_full_path |cut:"/ru/" }}">{% trans "Eng" %}</a> |
            {% elif LANGUAGE_CODE == 'en' %} 
            <a href="/ru/{{ request.get_full_path |cut:"/en/" }}">{% trans "Rus" %}</a> |
            {% endif %}
            <a href="{% url "account:dashboard"%}">{% trans "My Account" %}</a> | <a href="{% url "account:wishlist"%}">{% trans "My Wishlist" %}</a> |
            <a href="{% url "basket:basket_summary"%}">{% trans "My Cart" %}</a> | 
            {% if not request.user.is_authenticated %}
            <a href="{% url "account:login"%}">{% trans "Log In" %}</a></p>
            {% elif request.user.is_authenticated %}
            <a href="{% url "account:logout"%}">{% trans "Logout" %}</a></p>
            <p>
            {% endif%}
                        {% with total_qty=basket|length %}
                        {% trans " Shopping Cart:" %} 
                        <strong id='basket-qty'>
                        {% if total_qty > 0 %}
                        {{ total_qty }}
                        {% else %}
                        0
                        {% endif %}
                        </strong> {% trans "item's" %} ( <a href="{% url "basket:basket_summary"%}">{% trans "Show Cart" %}</a> )
                        {% endwith %}
            </p>
        </div>
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_header -->
    <div id="templatemo_menubar">
        <div id="top_nav" class="ddsmoothmenu">
            <ul>
                <li>
                    {% if LANGUAGE_CODE == 'en' %}
                    <a href="/en/" class="selected">{% trans "Home" %}</a>
                    {% elif LANGUAGE_CODE == 'ru' %}
                    <a href="/ru/" class="selected">{% trans "Home" %}</a>p
                    {% endif %}
                </li>
                <li><a href="{% url "shopsw:about_us" %}">{% trans "About" %}</a>
                </li>
                <li><a href="{% url "shopsw:faqs" %}">{% trans "FAQs" %}</a></li>
                <li><a href="{% url "shopsw:contact" %}">{% trans "Contact Us" %}</a></li>
            </ul>
            <br style="clear: left" />
        </div> <!-- end of ddsmoothmenu -->
        <div id="templatemo_search">
            <form action="#" method="get">
              <input type="text" value=" " name="keyword" id="keyword" title="keyword" onfocus="clearText(this)" onblur="clearText(this)" class="txt_field" />
              <input type="submit" name="Search" value=" " alt="Search" id="searchbutton" title="Search" class="sub_btn"  />
            </form>
        </div>
    </div> <!-- END of templatemo_menubar -->
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>