account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
from .forms import (
    UserLoginForm, PwdResetForm, PwdResetConfirmForm,
)
from django.views.generic import TemplateView

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/registration/login.html',
                                                form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/user/password_reset_form.html",
                                                                 success_url= 'password_reset_email_confirm',
                                                                 email_template_name='account/user/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset') ,
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/user/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm),
         name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/user/reset_status.html"), name='password_reset_complete'),
    # path('activate/<slug:uidb64>/<slug:token>)/', views.account_activate, name='activate'),
    path('dashboard/', views.dashboard, name='dashboard'),
    # Wish List
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="user_wishlist"),
]

basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns =  [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('shopsw.urls', namespace='shopsw')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopsw/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'shopsw'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('category/<slug:category_slug>', views.product_list, name='category_list'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('about_us/', views.about_us, name='about_us'),
    path('faqs/', views.faqs, name='faqs'),
    path('contact/', views.contact, name='contact'),
]

templates/about.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %} About us {% endblock %}
{% block content %}

</head>

<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">


    <div id="templatemo_main">
    	<div id="sidebar" class="float_l">
            <div class="sidebar_box"><span class="bottom"></span>
                <h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                    <ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>

        </div>
        <div id="content" class="float_r">
        	<h1>{% trans "About Us" %}</h1>
        	<h2>{% trans "Company Background" %}</h2>
        <p>{% trans "The sk.ua online market was created for the sale of women's, men's, children's shoes and accessories. SK.ua activities are distributed throughout Ukraine." %}</p>
        <div class="cleaner h20"></div>
        <h3>{% trans "Internet market provides" %}</h3>
		<p>{% trans "Shoes for you and your children. " %}
            {% trans "Information about changes in the price of goods and the appearance of discounts on them." %}
            {% trans "Lists of stores and online stores where you can purchase this shoe model." %}
            {% trans "Customer reviews of the model and her rating." %}
            {% trans "News reviews of collections, shows and fashion trends." %}
        {% trans "Articles on the correct choice, use, care and storage of shoes." %}</p>
        <div class="cleaner"></div>
        <blockquote>{% trans "all products are original" %}
        </blockquote>
        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->
    
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>
</html>
{% block scripts %}

{% endblock scripts %}
{% endblock %}

templates/base.html
{% load static %}
{% load i18n %}
{% block styles%}

<link href="/static/templatemo_style.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="/static/nivo-slider.css" type="text/css" media="screen" />
<link rel="stylesheet" type="text/css" href="/static/css/ddsmoothmenu.css" />
<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/ddsmoothmenu.js">

</script>

<script type="text/javascript">

ddsmoothmenu.init({
    mainmenuid: "top_nav", //menu DIV id
    orientation: 'h', //Horizontal or vertical menu: Set to "h" or "v"
    classname: 'ddsmoothmenu', //class added to menu's outer DIV
    // customtheme: ["#1c5a80", "#18374a"],
    contentsource: "markup" //"markup" or ["container_id", "path_to_menu_file"]
})

</script>
{% endblock styles%}
    {% include "includes/header.html" %}
     {% block content %}

     {% endblock %}
    {% include "includes/footer.html" %}

templates/contact.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_main">
        <div id="sidebar" class="float_l">
            <div class="sidebar_box"><span class="bottom"></span>
                <h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                    <ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="content" class="float_r">
        	<h1>{% trans "Contact Us" %}</h1>
            <div class="content_half float_l">
                <p>{% trans "We are located in the city of Ternopil Ukraine." %}</p>
                <div id="contact_form">
                   <form method="post" name="contact" action="#">
                        <center>
                                {% if form.errors %}
                                <p>Please correct the following errors:</p>
                                {% for field in form %}
                                {% if field.errors %}
                                <p style="color:red;">
                                <div class="alert alert-primary" role="alert">
                                    {{ field.label }}: {{ field.errors|striptags }}
                                </div>
                                </p>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                        </center>
                        <label for="author">{% trans "Name:" %}</label> <input type="text" id="author" name="username" class="required input_field" />
                        <div class="cleaner h10"></div>
                        <label for="email">{% trans "Email:" %}</label> <input type="text" id="email" name="email" class="validate-email required input_field" />
                        <div class="cleaner h10"></div>
                        
                        <label for="phone">{% trans "Phone:" %}</label> <input type="text" name="telephone" placeholder="+38(0**) ***-****" id="phone" class="input_field" />
                        <div class="cleaner h10"></div>
        
                        <label for="text">{% trans "Message:" %}</label> <textarea id="text" name="comment" rows="0" cols="0" class="required"></textarea>
                        <div class="cleaner h10"></div>
                        
                        <input type="submit" class="submit_btn" name="submit" id="submit" 
                        value="{% trans "Send" %} "  />
                        {% csrf_token %}
                    </form>
                </div>
            </div>
        <div class="content_half float_r">
        	<h5>{% trans "Primary Office" %}</h5>
            {% trans "Ukraine, Ternopil" %}
			{% trans "Phone:" %} 010-010-6600<br />
			{% trans "Email: " %}<a href="mailto:info@yourcompany.com">sergiykov94@gmail.com</a><br/>
			
            <div class="cleaner h40"></div>
        </div>
        
        <div class="cleaner h40"></div>
        
<!--         <iframe width="680" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Central+Park,+New+York,+NY,+USA&amp;aq=0&amp;sll=14.093957,1.318359&amp;sspn=69.699334,135.263672&amp;vpsrc=6&amp;ie=UTF8&amp;hq=Central+Park,+New+York,+NY,+USA&amp;ll=40.778265,-73.96988&amp;spn=0.033797,0.06403&amp;t=m&amp;output=embed"></iframe> -->
            
        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->
    
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>
</html>
{% block scripts %}

{% endblock scripts %}
{% endblock %}

templates/faqs.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">
    <div id="templatemo_main">
        <div id="sidebar" class="float_l">
            <div class="sidebar_box"><span class="bottom"></span>
                <h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                    <ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="content" class="float_r faqs">
        	<h1>{% trans "FAQs" %}</h1>
            <h5>{% trans "What is Try and Buy Service?" %}</h5>
            <p>{% trans "This service entitles you to try out your purchases at the time of delivery, pay only for what you like and return the rest on-the-spot. Try and Buy is a paid service, available on most of the products and in 31 Cities, you can enter pin code on product page to check service availability. Try and Buy is only available on orders containing items in cart. To avail this service min. order value should be Rs.1199 and above. To avail the service, please ensure that you tick the 'Try and Buy' box on check-out page and choose delivery address where you are comfortable trying product. Terms of service may differ for our new customers" %}
            </p>
            
          <h5>{% trans "How do I cancel the order, I have placed?" %}</h5>
            <p>{% trans "Order can be canceled till the same is out for delivery. Note: This may not be applicable for certain logistics partner. You would see an option to cancel within 'My Orders' section under the main menu of your App/Website/M-site then select the item or order you want to cancel. In case you are unable to cancel the order from'My Orders' section, you can refuse it at the time of delivery and refund will be processed into the source account, if order amount was paid online." %}</p>
            
            <h5>{% trans "What payment methods do you accept?" %}</h5>
            <p>{% trans "PayPal and 2Checkout (2CO)" %}</p>
            
            <h5>{% trans "How do I know if online ordering is secured?" %}</h5>
            <p>
            {% trans "Protecting your information is a  top priority for this site. We use Secure Sockets Layer (SSL) to encrypt your  credit card number, name and address, so only this site is able to decode  your information. SSL is the industry standard method for computers to  communicate securely without risk of data interception, manipulation or  recipient impersonation. To be sure your connection is secure; when you are in  the Shopping Cart, look at the lower corner of your browser window. If you see  an unbroken key or closed lock, the SSL is active and your information is  secure. Since most of the customers are still uncomfortable with providing your  credit card online, we use PayPal and 2CheckOut services and they do not need to  give out credit card information." %}</p>
          <p>
          {% trans "This site is registerd with HackerGuardian. HackerGuardian certification for  a hacker free website and a Credit Card TrustLogo confirming your  trustworthiness to take credit card details online." %}</p>

			
            <h5>{% trans "What is your privacy policy?" %}</h5>
            <p>{% trans "This website respects your privacy and ensure that  you understand what information we need to complete your order, and what  information you can choose to share with us and with our marketing partners.  For complete information on our privacy policy, please visit our " %}<a href="#">{% trans "Privacy Policy" %}</a>  {% trans "page." %}</p>
        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->

</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>
</html>
{% block scripts %}

{% endblock scripts %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<body>
<!--  -->
<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_main">
    	<div id="sidebar" class="float_l">
        	<div class="sidebar_box"><span class="bottom"></span>
            	<h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                	<ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="content" class="float_r">
        	<div id="slider-wrapper">
                <div id="slider" class="nivoSlider">
                    {% for slider in sliders %}
                    <a href="#"><img src="{{ slider.image.url }}" alt="" width="600" height="336" ></a>
                    {% endfor %}
                </div>

            </div>

        	<h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
            {% for product in page_obj %}
            <div class="product_box">
	            <h3>{{ product.name }}</h3>
            	<img src="{% if product.image %}{{ product.image.url }}{% endif %}"width="200" height="200">
                <p>{{ product.description|slice:":50" }}</p>
                <p class="product_price">{{product.price}}</p>
                <!-- <a href="shoppingcart.html" class="addtocart"></a> -->
                <a href="{{ product.get_absolute_url }}" class="detail"></a>
            </div>
            {% endfor %}

            <div class="cleaner"></div>

            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>

            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>

        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>
{% block scripts %}

            <script type="text/javascript" src="/static/js/jquery-1.4.3.min.js"></script>
            <script type="text/javascript" src="/static/js/jquery.nivo.slider.pack.js"></script>
            <script type="text/javascript">
            $(window).load(function() {
                $('#slider').nivoSlider();
            });
            </script>
{% endblock scripts %}
{% endblock %}

templates/productdetail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">
    
    <div id="templatemo_main">
    	<div id="sidebar" class="float_l">
        	<div class="sidebar_box"><span class="bottom"></span>
                <h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                    <ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="content" class="float_r">
        	<h1>{{ product.name }}</h1>
            <div class="content_half float_l">
        	<a  rel="lightbox[portfolio]" href="images/product/10_l.jpg"><img src="{% if product.image %}{{ product.image.url }}{% endif %}"  width="275" height="250"></a>
            </div>
            <div class="content_half float_r">
                <table>
                    <tr>
                        <td width="160">{% trans "Price:" %}</td>
                        <td>{{ product.price }}</td>
                    </tr>
                    <tr>
                        <td>{% trans "Availability:" %}</td>
                        <td>{% if product.available %} {% trans "Available" %}{% endif %}</td>
                    </tr>
                    <tr>
                    	<td>Quantity</td>
                        <td><select id="select" style="width: 40px; text-align: center" />
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            </select>
                        </td>
                    </tr>
                </table>

            <!-- add cart -->
                <div class="cleaner h20"></div>
                <button type="button" id="add-button" value="{{product.id}}" class="addtocart">{% trans "Add to basket" %}</button><br><br>
                <a href="{% url "account:user_wishlist" product.id %}">{% trans "Add to wishlist" %}</a><br>
			</div>
            </div>
            <div class="cleaner h20"></div>


            <div class="cleaner h30"></div>
            
            <h5>{% trans "Product Description" %}</h5>
            <p>{{product.description }}
            
          <div class="cleaner h50"></div>
        </div> 
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->

    
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    $(document).on('click', '#add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $('#add-button').val(),
                productqty: $('#select option:selected').text(),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
               document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

            <script type="text/javascript" src="/static/js/jquery-1.4.3.min.js"></script>
            <script type="text/javascript" src="/static/js/jquery.nivo.slider.pack.js"></script>
            <script type="text/javascript">
            $(window).load(function() {
                $('#slider').nivoSlider();
            });
            </script>

{% endblock scripts %}
{% endblock %}