basket/urls.py
from django.urls import path
from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
]

coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('accept/', views.coupon_apply, name='accept'),

]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns =  [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('', include('shopsw.urls', namespace='shopsw')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('accounts/', include('allauth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopsw/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'shopsw'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('category/<slug:category_slug>', views.product_list, name='category_list'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('about_us/', views.about_us, name='about_us'),
    path('faqs/', views.faqs, name='faqs'),
    path('contact/', views.contact, name='contact'),
]

basket/models.py
from django.db import models

basket/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from shopsw.models import Product
from .basket import Basket
from coupons.forms import CouponApplyForm

def basket_summary(request):

    basket = Basket(request)
    return render(request, 'basket/shoppingcart.html', {'basket': basket})


def basket_add(request):
    """
        Function should add product to basket
    """
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})

        return response

def basket_delete(request):
    """
        Function should delete product from basket
    """
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        
        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response

templates/basket/shoppingcart.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}Basket Summary

{% endblock %}
{% block styles%}

<link href="/static/templatemo_style.css" rel="stylesheet" type="text/css" />

<link rel="stylesheet" type="text/css" href="/static/css/ddsmoothmenu.css" />

<script type="text/javascript" src="/static/js/jquery.min.js"></script>
<script type="text/javascript" src="/static/js/ddsmoothmenu.js">

/***********************************************
* Smooth Navigational Menu- (c) Dynamic Drive DHTML code library (www.dynamicdrive.com)
* This notice MUST stay intact for legal use
* Visit Dynamic Drive at http://www.dynamicdrive.com/ for full source code
***********************************************/

</script>
{% endblock styles%}
{% block content %}<!-- templatemo 367 shoes -->

<body>

<div id="templatemo_body_wrapper">
<div id="templatemo_wrapper">

    <div id="templatemo_main">
    	<div id="sidebar" class="float_l">
        	<div class="sidebar_box"><span class="bottom"></span>
                <h3>{% trans "Categories" %}</h3>   
                <div class="content"> 
                    <ul class="sidebar_list">
                    <li {% if not category %}class="selected"{% endif %}>
                    <a href="{% url "shopsw:product_list" %}">{% trans "All" %}</a>
                    </li>
                    {% for c in categories %}
                    <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                    </li>
                    {% endfor %}
                    </ul>
                </div>
                <center><h4>Coupon</h4></center>
                <form action="{% url "coupons:accept" %}" method="post">
                <input type="hidden" name="current_url" value={{request.path}}> 
                <input type="text" id="user" name='code' >
                <input type="submit" >
                
                {% csrf_token %}
                
            </form>
            {% if basket.coupon %}
            {% with code=basket.coupon.code discount=basket.coupon.discount %}
                {{ code }} coupon {{discount }} % off
                {% endwith %}
            {% endif %}
            </div>
            
        </div>
        <div id="content" class="float_r">
            {% if basket %}
        	<h1>{% trans "Shopping Cart" %}</h1>
        	<table width="680px" cellspacing="0" cellpadding="5">
                   	  <tr bgcolor="#ddd">
                        	<th width="220" align="left">{% trans "Image" %} </th> 
                        	<th width="180" align="left">{% trans "Model" %} </th> 
                       	  	<th width="100" align="center">{% trans "Quantity" %} </th> 
                        	<th width="60" align="right">{% trans "Price" %} </th> 
                        	<th width="60" align="right">{% trans "Total" %} </th> 
                        	<th width="90"> </th>
                            
                      </tr>
                            {% for item in basket %}
                            {% with product=item.product%}
                    	<tr data-index="{{product.id}}" class="row mb-4 border product-item">
                        	<td><img src="{{ product.image.url }}" width="175" height="175" /></td> 
                        	<td>{{ product.name }}</td> 
                            <td align="center">{{ item.qty }} </td>
                            <td align="right">{{ item.price }} </td> 
                            <td align="right">{{ item.total_price}}</td>
                
                            <td align="center"> <button type="button" id="delete-button" data-index="{{product.id}}"  class="btn btn-outline-secondary btn-sm delete-button">{% trans "delete" %}</button> </td>
						</tr>

                    {% endwith %}
                    {% endfor %}

                        
                        <tr>
                        	<td colspan="3" align="right"  height="30px">{% trans "You total price:" %} &nbsp;&nbsp;</td>
                            <td align="right" style="background:#ddd; font-weight:bold"> Total </td>
                            <td align="right" style="background:#ddd; font-weight:bold" id="subtotal">{{ basket.get_total_price}} </td>
                            <td style="background:#ddd; font-weight:bold"> </td>
						</tr>
                        {% if basket.coupon %}
                        <tr>
                            <td colspan="3" align="right"  height="30px">{% trans "Discount :" %} &nbsp;&nbsp;</td>
                            <td align="right" style="background:#ddd; font-weight:bold"> </td>
                            <td align="right" style="background:#ddd; font-weight:bold" id="subtotal">{{ basket.get_discount }} </td>
                            <td style="background:#ddd; font-weight:bold"> </td>
                        </tr>
                        <tr>
                            <td colspan="3" align="right"  height="30px">{% trans "With Discount :" %} &nbsp;&nbsp;</td>
                            <td align="right" style="background:#ddd; font-weight:bold"> </td>
                            <td align="right" style="background:#ddd; font-weight:bold" id="subtotal">{{ basket.get_total_price_after_discount }} </td>
                            <td style="background:#ddd; font-weight:bold"> </td>
                        </tr>
                        {% endif %}


                </table>


                    <div style="float:right; width: 215px; margin-top: 20px;">
                    
					<p><a href="{% url "orders:order_create"%}">{% trans "Proceed to checkout" %}</a></p>
                    <p><a href="{{categories.first.get_absolute_url}}">{% trans "Continue shopping" %}</a></p>
                    	
                    </div>
            {% else%}
            <center>
            <h1>{% trans "You cart is empty" %}</h1>
            {% trans "Go to shop and choose some shoe" %}
            {% endif %}

                
		</div>
        <div class="cleaner"></div>
    </div> <!-- END of templatemo_main -->


        
    
</div> <!-- END of templatemo_wrapper -->
</div> <!-- END of templatemo_body_wrapper -->

</body>
</html>

{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var prodid = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post'
            },
            success: function (json) {
                console.log(prodid)
                $('.product-item[data-index="' + prodid + '"]').remove();
                document.getElementById("subtotal").innerHTML = json.subtotal;
                document.getElementById("basket-qty").innerHTML = json.qty
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock scripts %}
{% endblock %}